In [1]:
import os
import pandas as pd

In [4]:
ticker = "AAPL"

cwd = os.getcwd()

csv_path = os.path.join(cwd, "..", "..", "tickers", ticker, "financials_2025-05-25.csv")
csv_path = os.path.abspath(csv_path)

df = pd.read_csv(csv_path)
df

,dimension,calendardate,datekey,reportperiod,fiscalperiod,workingcapital,marketcap,lastupdated,accoci,assets,...,sharefactor,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps
0,ARQ,1993-12-31,1994-01-26,1993-12-31,1994-Q1,1.879846e+09,3.926233e+09,2025-05-02,-2.650900e+07,5.042440e+09,...,1.0,1.313121e+10,1.309907e+10,1.309907e+10,0.188,5.042440e+09,279198000.0,2.452600e+07,663906000.0,0.385
1,ARQ,1994-06-30,1994-08-12,1994-07-01,1994-Q3,2.342502e+09,4.133103e+09,2025-05-02,-1.547400e+07,5.123412e+09,...,1.0,1.332185e+10,1.332185e+10,NaN,0.161,5.123412e+09,256945000.0,8.464200e+07,655995000.0,0.385
2,ARQ,1994-09-30,1994-12-13,1994-09-30,1994-Q4,2.532147e+09,4.360691e+09,2025-05-02,-1.083400e+07,5.302746e+09,...,1.0,1.342784e+10,1.329832e+10,NaN,0.187,5.302746e+09,293048000.0,7.027200e+07,670668000.0,0.399
3,ARQ,1994-12-31,1995-02-09,1994-12-30,1995-Q1,2.783000e+09,5.268122e+09,2025-05-02,-1.700000e+07,5.533000e+09,...,1.0,1.352535e+10,1.361922e+10,1.361922e+10,0.208,5.533000e+09,269000000.0,1.110000e+08,732000000.0,0.406
4,ARQ,1995-03-31,1995-05-15,1995-03-31,1995-Q2,2.918000e+09,5.285418e+09,2025-05-02,4.400000e+07,6.050000e+09,...,1.0,1.356975e+10,1.373613e+10,1.373613e+10,0.193,6.050000e+09,350000000.0,4.300000e+07,789000000.0,0.440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,MRY,2020-12-31,2020-09-26,2020-09-26,2020-FY,3.832100e+10,1.920273e+12,2025-05-02,-4.060000e+08,3.238880e+11,...,1.0,1.710254e+10,1.735212e+10,1.752821e+10,15.820,3.238880e+11,0.0,9.680000e+09,0.0,18.666
567,MRY,2021-12-31,2021-09-25,2021-09-25,2021-FY,9.355000e+09,2.428612e+12,2025-05-02,1.630000e+08,3.510020e+11,...,1.0,1.653017e+10,1.670127e+10,1.686492e+10,21.904,3.510020e+11,0.0,1.452700e+10,0.0,21.016
568,MRY,2022-12-31,2022-09-24,2022-09-24,2022-FY,-1.857700e+10,2.417523e+12,2025-05-02,-1.110900e+10,3.527550e+11,...,1.0,1.607075e+10,1.621596e+10,1.632582e+10,24.317,3.527550e+11,0.0,1.930000e+10,0.0,21.754
569,MRY,2023-12-31,2023-09-30,2023-09-30,2023-FY,-1.742000e+09,2.676737e+12,2025-05-02,-1.145200e+10,3.525830e+11,...,1.0,1.563423e+10,1.574423e+10,1.581255e+10,24.344,3.525830e+11,0.0,1.674100e+10,0.0,22.394
570,MRY,2024-12-31,2024-09-28,2024-09-28,2024-FY,-2.340500e+10,3.463350e+12,2025-05-02,-7.172000e+09,3.649800e+11,...,1.0,1.520414e+10,1.534378e+10,1.540810e+10,25.485,3.649800e+11,0.0,2.974900e+10,0.0,23.787